package com.example.challenge2_binar.produk

import com.example.challenge2_binar.R

object Menu {
    val menu : List<Any>
        get() = mutableListOf(
            MenuList(R.drawable.pizza,
                "Pizza ala Binar",
                89000,
                "Topping daging sapi yang lembut dipadu dengan rempah-rempah dan bumbu, menciptakan cita rasa istimewa yang memanjakan lidah",
                "Cafe Terbinarbinar",
                "Jl. Binar Academy, Semoga dapet nilai besar. Astungkara 100x",
                "https://maps.app.goo.gl/h4wQKqaBuXzftGK77"),
            MenuList(R.drawable.aym_panggang,
                "Ayang Bakar",
                50000,
                "Daging ayam yang lembut dipadu dengan rempah-rempah dan bumbu, menciptakan cita rasa istimewa yang memanjakan lidah",
                "Jl. Mahendradatta Selatan No.30x Kota Denpasar, Bali",
                "Ayam Bakar Wo Ai Ni",
                "https://maps.app.goo.gl/qvNGaK2dVMe9vTPJ7"),
            MenuList(R.drawable.mie_kuah,
                "Mie kuah ala Binar",
                35000,
                "Topping daging sapi yang lembut dipadu dengan rempah-rempah dan bumbu,menciptakan cita rasa istimewa yang memanjakan lidah",
                "Cafe Terbinarbinar",
                "Jl. Binar Academy, Semoga dapet nilai besar. Astungkara 100x",
                "https://maps.app.goo.gl/h4wQKqaBuXzftGK77"),
            MenuList(R.drawable.sate_ayamm,
                "Sate Ayam",
                40000,
                "Daging ayam yang lembut dipadu dengan rempah-rempah dan bumbu,menciptakan cita rasa istimewa yang memanjakan lidah",
                "Sate Ayam RSPP Jakarta",
                "Jl. Sunset Road No.100, Kuta, Kabupaten Badung, Bali 80361",
                "https://maps.app.goo.gl/Rd3pn6g3HZzn3fM59"),
            MenuList(R.drawable.spaghetti_pasta,
                "Spaghetti ala Binar",
                89000,
                "Topping daging sapi yang lembut dipadu dengan rempah-rempah dan bumbu, menciptakan cita rasa istimewa yang memanjakan lidah",
                "Cafe Terbinarbinar",
                "Jl. Binar Academy, Semoga dapet nilai besar. Astungkara 100x",
                "https://maps.app.goo.gl/h4wQKqaBuXzftGK77"),
            MenuList(R.drawable.dimsum,
                "Dimsum Udang",
                30000,
                "Topping daging udang yang lembut dipadu dengan rempah-rempah dan bumbu, menciptakan cita rasa istimewa yang memanjakan lidah",
                "Dim Sum Inc.",
                "Jl. Dewi Sri No.101, Legian, Kec. Kuta, Kabupaten Badung, Bali 80361",
                "https://maps.app.goo.gl/ET1FBMqjPwaNmXyR7"),
            MenuList(R.drawable.ayamgorengg,
                "Ayam Goreng Rempah",
                75000,
                "Daging ayam yang lembut dipadu dengan rempah-rempah dan bumbu, menciptakan cita rasa istimewa yang memanjakan lidah",
                "Seeds Eatery",
                "Jl. Raya Pengosekan Ubud, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",
                "https://maps.app.goo.gl/zGdTXseDXocy7ndLA"),
            MenuList(R.drawable.coffeeandcroisant,
                " Bundle Coffee",
                45000,
                "Cita rasa kopi susu yang creamy dengan menggunkan oatmilk dipadukan dengan plaint Croissant menciptakan cita rasa istimewa",
                "Pison, Ubud",
                "Jl. Hanoman No.10X, Ubud, Kecamatan Ubud, Kabupaten Gianyar, Bali 80571",
                "https://maps.app.goo.gl/M2U96njvJ2mapyRt8"),
        )

}